### ISSUE TITLE
InputStream vs Array[Byte] vs Iterator[Byte] vs Traversable[Byte]

### ISSUE THREAD

**Issue by evdokim** [ohnosequences/aws-scala-tools#12]
@eparejatobes @laughedelic 
We should decide which type we will use for content of requests in saws-sign library.

## InputStream
Widely used in AWS SDK, dispatch, async-http-client. Worth thing from my point of view because if you pass it to other method, it should call reset on it in the end (otherwise we will send not all body of requests)

## Iterator[Byte], Traversable[Byte]
It is possible to wrap ```InputStream``` to something more safe, for example to ```Traversable[Byte]``` that will be reset internal ```InputStream``` after each ```foreach()```. Such wrappers have been already implemented in ```scalax.io```. 

##  Array[Byte]
Most safe approach, ant manipulations with this array can't change original body of request. But it has limitation: we should store in memory whole body of request.
Actually amazon guys do it for S3 signing:
```java
// com.amazonaws.auth.AWS3Signer

    protected byte[] getBinaryRequestPayloadWithoutQueryParams(Request<?> request) {
    	InputStream content = getBinaryRequestPayloadStreamWithoutQueryParams(request);

    	try {
            content.mark(-1);
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024 * 5];
            while (true) {
            	int bytesRead = content.read(buffer);
            	if (bytesRead == -1) break;

            	byteArrayOutputStream.write(buffer, 0, bytesRead);
            }

            byteArrayOutputStream.close();
            content.reset();

            return byteArrayOutputStream.toByteArray();
        } catch (Exception e) {
            throw new AmazonClientException("Unable to read request payload to sign request: " + e.getMessage(), e);
        }
    }
```
this code put all body of request to ```byteArrayOutputStream```.

Thus I suggest so far use ```Array[Byte]```, but it is unnecessary to consider big requests and to get know limitations for requests. I think that for some services (SQS for e.g.) request size are limited.

**Comment by laughedelic** [comment]
I think nobody cares about this anymore. Closing
