### ISSUE TITLE
Take a look on the current existing scala aws libraries 

### ISSUE THREAD

**Issue by evdokim** [ohnosequences/aws-scala-tools#3]
* https://github.com/Rhinofly/play-aws-utils - looks, uses Play WS client
* https://github.com/n8han/dispatch-aws-s3

**Comment by laughedelic** [comment]
- chat: https://gitter.im/awslabs/aws-scala-sdk
- and a [google doc table](https://docs.google.com/spreadsheets/d/1tPX1YVQhE1RXpnZNrTPhm0o0FJOPXsauYC9zVKy4ikg/edit?usp=sharing)
