### ISSUE TITLE
i3 instances support HVM

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/aws-scala-tools#58]

**Comment by laughedelic** [comment]
They do:

```
scala> import ohnosequences.awstools._, ec2._
scala> implicitly[i3.large.type SupportsVirtualization HVM.type]
res3: ohnosequences.awstools.ec2.SupportsVirtualization[ohnosequences.awstools.ec2.i3.large.type,ohnosequences.awstools.ec2.HVM.type] = ohnosequences.awstools.ec2.SupportsVirtualization$$anon$16@36abe5a0
```

All instance types of the current generation support HVM and it's defined this way in the lib:

https://github.com/ohnosequences/aws-scala-tools/blob/b87a1ce6e35f2de33d65e8b3ce94c79703f1873e/src/main/scala/ohnosequences/awstools/ec2/InstanceType-AMI.scala#L133-L135
